## Index/config.yml
---
Index:
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: NO
  favourite_control: NO
  help_file: help.html.twig
  title: Men√∫ Prinpical
  id_video: index
  url_video: null
  conection: 'Cpanel'
  entity: index